# Generated by Django 4.2 on 2023-07-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_publicationbox_publication_kind_publication_loc_and_more'),
        ('djangocms_googlemap', '0012_alter_googlemap_cmsplugin_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemap',
            name='locations',
            field=models.ManyToManyField(blank=True, help_text='Wähle die anzuzeigenden Standorte aus', to='organization.location', verbose_name='Standorte'),
        ),
    ]
