# Generated by Django 4.2 on 2023-07-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_publicationbox_publication_kind_publication_loc_and_more'),
        ('djangocms_googlemap', '0013_googlemap_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlemap',
            name='locations',
            field=models.ManyToManyField(blank=True, help_text='Wähle die anzuzeigenden Standorte aus. Standorte ohne Einrichtungstyp oder vom Typ "Webseitenbereich" werden nicht berücksichtigt.', to='organization.location', verbose_name='Standorte'),
        ),
    ]
